name: Publisher

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Run script
        env:
          REPO_TOKEN: ${{ secrets.CLIN_FHIR_DEPLOY_KEY }}
        run: |
          SCRIPT=.github/build.sh
          if [ -f $SCRIPT ]; then 
            chmod u+x $SCRIPT
            $SCRIPT
          fi
